/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export const translations = {
  en: {
    // General
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    addItem: 'Add Item',
    loading: 'Loading item...',
    saving: 'Saving...',
    loadingCollection: 'Loading collection...',
    exportBackup: 'Export Backup',
    importBackup: 'Import Backup',
    importWarning: 'Warning: Importing this backup will completely REPLACE your current collection and wishlist. Unsaved progress will be lost. Are you sure you want to proceed?',
    importWarningKeepsWishlist: 'Warning: This backup was made before the wishlist existed. Importing it will completely REPLACE your current collection and keep your current wishlist. Are you sure you want to proceed?',
    importSuccess: 'Backup imported successfully!',
    importError: 'Invalid backup file or corrupted payload version.',
    exportError: 'Export failed. Database might be empty or corrupted.',
    backupTitle: 'Backup',
    errorTitle: 'Something went wrong',
    successTitle: 'Completed',
    continue: 'Continue',
    close: 'Close',
    importSafetyBackup: 'A safety backup of your current collection and wishlist will be downloaded before replacement.',
    noPhoto: 'No Photo',
    unknownCharacter: 'Unknown Character',
    unknownSeries: 'Unknown Series',
    addedOn: 'Added on',
    editItem: 'Edit Item',
    newItem: 'New Item',
    usageGuide: 'User guide',
    versionLabel: 'Version {version}',
    privacyPolicy: 'Privacy',
    sendFeedback: 'Send feedback',
    thirdPartyNotices: 'Third-party notices',
    
    // Home
    myCollection: 'My Collection',
    searchPlaceholder: 'Search series, character, type, notes...',
    noItemsFound: 'No items found',
    tryAdjusting: 'Try adjusting your filters or add a new item.',
    language: 'Language',
    importFile: 'Import backup file',
    searchLabel: 'Search collection',
    filterTypeLabel: 'Filter by merchandise type',
    filterSeriesLabel: 'Filter by series',
    filterCharacterLabel: 'Filter by character',
    showingItems: 'Showing {start}–{end} of {total}',
    previousPage: 'Previous',
    nextPage: 'Next',
    pageOf: 'Page {page} of {pages}',
    storageLabel: 'Browser storage',
    storageUsage: '{used} of {quota} used',
    storagePersistent: 'Protected from automatic eviction',
    storageBestEffort: 'May be removed when device storage is low',
    protectStorage: 'Protect local data',
    storageWarning: 'Browser storage is nearly full. Export a backup and remove large photos or old items.',
    persistenceGranted: 'Persistent storage has been enabled.',
    persistenceDenied: 'This browser did not grant persistent storage. Keep regular backups.',
    
    // Form & Detailed
    seriesFranchise: 'Series / Franchise',
    seriesPlaceholder: 'e.g. Neon Genesis Evangelion',
    character: 'Character',
    characterPlaceholder: 'e.g. Asuka Langley Soryu',
    merchandiseType: 'Merchandise Type',
    notesOptional: 'Notes (Optional)',
    notesPlaceholder: 'Condition, price, origin, etc.',
    notes: 'Notes',
    deleteConfirm: 'Are you sure you want to delete this item?',
    deleteTitle: 'Delete item?',
    deleteError: 'Failed to delete this item. Please try again.',
    validationRequireOne: 'Please enter at least a series or character.',
    validationRequireType: 'Please select a merchandise type.',
    saveError: 'Failed to save item. Storage might be full.',
    itemNotFound: 'This item does not exist or has already been deleted.',
    backHome: 'Back to collection',
    routeNotFoundTitle: 'Page not found',
    routeNotFoundMessage: 'That address is not part of this app. Your collection is still safe on this device.',
    unexpectedErrorTitle: 'The app could not continue',
    unexpectedErrorMessage: 'Your local data has not been intentionally changed. Reload the app, then export a backup if the problem continues.',
    reloadApp: 'Reload app',
    
    // Types
    allTypes: 'All Types',
    figure: 'Figure/Statue',
    plush: 'Plush',
    acrylic: 'Acrylic Stand',
    badge: 'Badge/Pin',
    apparel: 'Apparel',
    poster: 'Poster/Print',
    other: 'Other',
    
    // Uploader
    addPhoto: 'Add Photo',
    tapToTake: 'Tap to take photo or choose from gallery',
    tapToChange: 'Tap to change',
    photoPreview: 'Selected item preview',
    removePhoto: 'Remove photo',
    typeToSearch: 'Type to search or add...',
    addSelfDefinedType: 'Add self-defined type...',
    addMultiValue: 'Add "{value}"',
    removeMultiValue: 'Remove {value}',
    allSeries: 'All Series',
    allCharacters: 'All Characters',
    exportLargeTitle: 'Large backup',
    exportLargeMessage: 'This backup is larger than the import limit ({size} of {limit}). The file will still download, but restoring it may fail or run out of memory. Consider removing large photos or old items first.',

    // Lists
    listsLabel: 'Lists',
    collectionTab: 'Collection',
    wishlistTab: 'Wishlist',

    // Wishlist
    wishlist: 'Wishlist',
    loadingWishlist: 'Loading wishlist...',
    wishlistSearchLabel: 'Search wishlist',
    wishlistSearchPlaceholder: 'Search name, series, character, shop, links...',
    filterStatusLabel: 'Filter by status',
    allStatuses: 'All statuses',
    statusWant: 'Want',
    statusOrdered: 'Ordered',
    filterPriorityLabel: 'Filter by priority',
    allPriorities: 'All priorities',
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',
    highPriority: 'High priority',
    sortLabel: 'Sort wishlist',
    sortNewest: 'Newest first',
    sortDeadline: 'Order deadline first',
    sortPriority: 'Highest priority first',
    quickAdd: 'Add screenshots',
    quickAddFiles: 'Choose screenshots',
    quickAddHint: 'Choose several photos or screenshots at once. Each becomes its own entry to fill in later.',
    quickAddProgress: 'Adding screenshots...',
    quickAddDone: 'Added {count} entries. Open each one to fill in the details.',
    quickAddTooMany: 'Choose up to {max} images at a time.',
    quickAddNoImages: 'None of the chosen files is an image.',
    wishlistEmpty: 'Your wishlist is empty',
    wishlistEmptyHint: 'Add a photo or screenshot of merchandise you want to buy.',
    noEntriesFound: 'No entries found',
    tryAdjustingWishlist: 'Try adjusting your search or filters.',
    addWishlistEntry: 'Add to Wishlist',
    newWishlistEntry: 'New Wishlist Entry',
    editWishlistEntry: 'Edit Wishlist Entry',
    untitledEntry: 'Untitled',
    orderBy: 'Order by {date}',
    deadlinePassed: 'Deadline passed ({date})',
    wishlistFormHint: 'Every field is optional. An entry needs at least a photo, a name, or a link.',
    entryName: 'Name',
    entryNamePlaceholder: 'e.g. Asuka 1/7 scale figure',
    links: 'Links',
    linkAddress: 'Link {index} address',
    linkLabel: 'Link {index} label',
    linkLabelPlaceholder: 'Label (optional)',
    addLink: 'Add link',
    removeLink: 'Remove link {index}',
    price: 'Price',
    currency: 'Currency',
    shop: 'Shop',
    shopPlaceholder: 'e.g. AmiAmi',
    orderDeadline: 'Order deadline',
    release: 'Release',
    releasePlaceholder: 'e.g. March 2027',
    priority: 'Priority',
    status: 'Status',
    noType: 'Not specified',
    wishlistRequireOne: 'Add a photo, a name, or a link.',
    wishlistInvalidLink: 'This link is not a web address (http or https): {value}',
    wishlistInvalidPrice: 'Enter a price of 0 or more, using numbers only.',
    deleteWishlistTitle: 'Delete wishlist entry?',
    deleteWishlistConfirm: 'Are you sure you want to delete this wishlist entry?',
    wishlistEntryNotFound: 'This wishlist entry does not exist or has already been deleted.',
    backWishlist: 'Back to wishlist',
    expandImage: 'Show the whole image',
    opensInNewTab: '(opens in a new tab)',
  },
  'zh-TW': {
    // General
    cancel: '取消',
    saveChanges: '儲存變更',
    addItem: '新增項目',
    loading: '載入中...',
    saving: '儲存中...',
    loadingCollection: '載入收藏中...',
    exportBackup: '匯出備份',
    importBackup: '匯入備份',
    importWarning: '警告：匯入這份備份將會完全覆蓋（取代）您目前的收藏與願望清單。確定要繼續嗎？',
    importWarningKeepsWishlist: '警告：這份備份建立於願望清單功能推出之前。匯入後將會完全覆蓋（取代）您目前的收藏，願望清單則保持不變。確定要繼續嗎？',
    importSuccess: '已經成功匯入備份！',
    importError: '無效的備份檔案或版本損毀。',
    exportError: '匯出失敗，資料庫可能異常或無資料。',
    backupTitle: '備份',
    errorTitle: '發生錯誤',
    successTitle: '已完成',
    continue: '繼續',
    close: '關閉',
    importSafetyBackup: '取代資料前，App 會先自動下載目前收藏與願望清單的安全備份。',
    noPhoto: '無照片',
    unknownCharacter: '未知角色',
    unknownSeries: '未知系列',
    addedOn: '新增於',
    editItem: '編輯項目',
    newItem: '新增項目',
    usageGuide: '使用說明',
    versionLabel: '版本 {version}',
    privacyPolicy: '隱私',
    sendFeedback: '問題回報',
    thirdPartyNotices: '第三方授權',
    
    // Home
    myCollection: '我的收藏',
    searchPlaceholder: '搜尋系列、角色、類型、備註...',
    noItemsFound: '找不到任何項目',
    tryAdjusting: '請嘗試調整過濾器或新增項目。',
    language: '語言',
    importFile: '匯入備份檔案',
    searchLabel: '搜尋收藏',
    filterTypeLabel: '依周邊類型篩選',
    filterSeriesLabel: '依作品系列篩選',
    filterCharacterLabel: '依角色篩選',
    showingItems: '顯示第 {start}–{end} 項，共 {total} 項',
    previousPage: '上一頁',
    nextPage: '下一頁',
    pageOf: '第 {page} 頁，共 {pages} 頁',
    storageLabel: '瀏覽器儲存空間',
    storageUsage: '已使用 {used}／{quota}',
    storagePersistent: '已保護，不會因空間壓力被自動清除',
    storageBestEffort: '裝置空間不足時可能被瀏覽器清除',
    protectStorage: '保護本機資料',
    storageWarning: '瀏覽器儲存空間快滿了。請匯出備份，並移除大型照片或舊項目。',
    persistenceGranted: '已啟用持久儲存空間。',
    persistenceDenied: '瀏覽器未授予持久儲存空間，請定期備份。',
    
    // Form & Detailed
    seriesFranchise: '作品系列',
    seriesPlaceholder: '例如：新世紀福音戰士',
    character: '角色名稱',
    characterPlaceholder: '例如：明日香',
    merchandiseType: '周邊類型',
    notesOptional: '備註 (選填)',
    notesPlaceholder: '商品狀況、價格、來源等',
    notes: '備註',
    deleteConfirm: '確定要刪除這個項目嗎？',
    deleteTitle: '刪除項目？',
    deleteError: '刪除失敗，請稍後再試。',
    validationRequireOne: '請至少輸入作品系列或角色名稱。',
    validationRequireType: '請選擇一個周邊類型。',
    saveError: '儲存失敗，儲存空間可能已滿。',
    itemNotFound: '這個項目不存在或已經被刪除。',
    backHome: '返回收藏',
    routeNotFoundTitle: '找不到頁面',
    routeNotFoundMessage: '這個網址不屬於這個 App。你的收藏仍安全保存在這台裝置上。',
    unexpectedErrorTitle: 'App 無法繼續執行',
    unexpectedErrorMessage: 'App 並未刻意變更您的本機資料。請重新載入；若問題持續，請儘快匯出備份。',
    reloadApp: '重新載入 App',
    
    // Types
    allTypes: '所有類型',
    figure: '模型/公仔',
    plush: '絨毛玩偶',
    acrylic: '壓克力立牌',
    badge: '徽章/別針',
    apparel: '服飾',
    poster: '海報/畫作',
    other: '其他',
    
    // Uploader
    addPhoto: '加入照片',
    tapToTake: '點擊拍照或從相簿選擇',
    tapToChange: '點擊更換',
    photoPreview: '已選商品照片預覽',
    removePhoto: '移除照片',
    typeToSearch: '直接輸入來搜尋或新增...',
    addSelfDefinedType: '新增自訂類型...',
    addMultiValue: '新增「{value}」',
    removeMultiValue: '移除 {value}',
    allSeries: '所有系列',
    allCharacters: '所有角色',
    exportLargeTitle: '備份檔過大',
    exportLargeMessage: '這份備份超過匯入上限（{size}，上限 {limit}）。檔案仍會下載，但還原時可能失敗或耗盡記憶體。建議先移除大張照片或舊項目。',

    // Lists
    listsLabel: '清單',
    collectionTab: '我的收藏',
    wishlistTab: '願望清單',

    // Wishlist
    wishlist: '願望清單',
    loadingWishlist: '載入願望清單中...',
    wishlistSearchLabel: '搜尋願望清單',
    wishlistSearchPlaceholder: '搜尋名稱、系列、角色、商店、連結...',
    filterStatusLabel: '依狀態篩選',
    allStatuses: '所有狀態',
    statusWant: '想買',
    statusOrdered: '已下單',
    filterPriorityLabel: '依優先度篩選',
    allPriorities: '所有優先度',
    priorityHigh: '高',
    priorityMedium: '中',
    priorityLow: '低',
    highPriority: '高優先',
    sortLabel: '願望清單排序',
    sortNewest: '最新加入',
    sortDeadline: '下單截止日優先',
    sortPriority: '優先度高者優先',
    quickAdd: '一次加入多張截圖',
    quickAddFiles: '選擇截圖',
    quickAddHint: '可一次選擇多張照片或截圖，每張各自成為一個項目，之後再補上細節。',
    quickAddProgress: '正在加入截圖...',
    quickAddDone: '已加入 {count} 個項目，點開即可補上細節。',
    quickAddTooMany: '一次最多選擇 {max} 張圖片。',
    quickAddNoImages: '選擇的檔案中沒有圖片。',
    wishlistEmpty: '願望清單是空的',
    wishlistEmptyHint: '加入想買周邊的照片或截圖。',
    noEntriesFound: '找不到任何項目',
    tryAdjustingWishlist: '請嘗試調整搜尋或篩選條件。',
    addWishlistEntry: '加入願望清單',
    newWishlistEntry: '新增願望清單項目',
    editWishlistEntry: '編輯願望清單項目',
    untitledEntry: '未命名',
    orderBy: '{date} 前下單',
    deadlinePassed: '已過截止日（{date}）',
    wishlistFormHint: '所有欄位皆為選填，但至少需要照片、名稱或連結其中一項。',
    entryName: '名稱',
    entryNamePlaceholder: '例如：明日香 1/7 比例模型',
    links: '連結',
    linkAddress: '連結 {index} 網址',
    linkLabel: '連結 {index} 標籤',
    linkLabelPlaceholder: '標籤 (選填)',
    addLink: '新增連結',
    removeLink: '移除連結 {index}',
    price: '價格',
    currency: '幣別',
    shop: '商店',
    shopPlaceholder: '例如：AmiAmi',
    orderDeadline: '下單截止日',
    release: '發售時間',
    releasePlaceholder: '例如：2027 年 3 月',
    priority: '優先度',
    status: '狀態',
    noType: '未指定',
    wishlistRequireOne: '請至少加入照片、名稱或連結其中一項。',
    wishlistInvalidLink: '這個連結不是網址（http 或 https）：{value}',
    wishlistInvalidPrice: '請只用數字輸入 0 以上的價格。',
    deleteWishlistTitle: '刪除願望清單項目？',
    deleteWishlistConfirm: '確定要刪除這個願望清單項目嗎？',
    wishlistEntryNotFound: '這個願望清單項目不存在或已經被刪除。',
    backWishlist: '返回願望清單',
    expandImage: '顯示完整圖片',
    opensInNewTab: '（在新分頁開啟）',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('appLang') || 'zh-TW';
  });

  useEffect(() => {
    localStorage.setItem('appLang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useCallback((key, values = {}) => {
    const template = translations[lang]?.[key] || translations.en[key] || key;
    return Object.entries(values).reduce(
      (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
      template,
    );
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
